import { Component, OnInit  } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DataService } from 'src/app/service/data.Service';
import { EmployeeService } from 'src/app/service/employee.service';
import { Chart, ChartOptions, ChartType, ChartDataset } from 'chart.js';
import { BaseChartDirective } from 'ng2-charts';
import { Employee } from 'src/app/shared/employee';
import { Employee_Role } from 'src/app/shared/EmployeeRole';
import { Gender } from 'src/app/shared/gender';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { saveAs } from 'file-saver';
import { UserStoreService } from 'src/app/UserService/user-store.service';
import { AuthService } from 'src/app/UserService/auth.service';

@Component({
  selector: 'app-employee',
  templateUrl: './employee.component.html',
  styleUrls: ['./employee.component.css']
})

export class EmployeeComponent implements OnInit {
  employees: Employee[] = [];
  employeeRoles: Employee_Role[] = [];
  genders: Gender[] = [];
  filteredEmployees: Employee[] = [];
  userName: string = "";

  isFilterActive = false;

  // Bar chart
  barChartOptions: ChartOptions = {
    responsive: true,
  };

  barChartLabels: any[] = [];
  barChartData: ChartDataset[] = [
    {
      data: [], // Array of employee counts
      label: 'Number of Employees',
    },
  ];
  barChartLegend = true;
  barChartType: ChartType = 'bar';

  // Pie Chart
  pieChartOptions: ChartOptions = {
    responsive: true,
  }
  pieChartLabels: any[] = [];
  pieChartData: ChartDataset[] = [
    {
      data: [], // Array of employee counts
      label: 'Number of Employees'
    }
  ];
  pieChartType: ChartType = 'pie';

  constructor(private http: HttpClient, 
    private dataService: DataService, 
    private employeeService: EmployeeService,
    private userService: UserStoreService,
    private auth: AuthService) { }

  ngOnInit() {
    this.fetchData()
    this.GetAllGenders()
  }

  fetchData()
  {
    this.dataService.GetAllEmployeeRoles().subscribe(result => {
      this.employeeRoles = result;
      this.GetAllEmployees();
    });
  }

  GetAllEmployees()
  {
    this.employeeService.GetAllEmployees().subscribe(result => {
      this.employees = result;
      this.generateBarChart();
    });
  }

  GetAllGenders()
  {
    this.employeeService.GetAllGenders().subscribe(result => {
      this.genders = result
      this.genders.forEach((element) => {
        this.genders.push(element)        
      });
    })
  }

  generateBarChart() {
    // Create a mapping object to store the count for each role
    const roleCountMap: { [roleName: string]: number } = {};
  
    // Count the employees for each role
    this.employees.forEach(emp => {
      const roleName  = emp.employeeRoleName;
      if (roleName ) {
        if (!roleCountMap.hasOwnProperty(roleName )) {
          roleCountMap[roleName ] = 1;
        } else {
          roleCountMap[roleName ]++;
        }
      }
    });
  
    // Use the employeeRoles array to get the role names for the chart labels
    const roleLabels = this.employeeRoles.map(role => role.name);
  
    // Map the counts to the corresponding roles for the chart data
    const employeeCountData = roleLabels.map(roleName => roleCountMap[roleName] ||0);  
  
    // Update the chart data and labels for BAR GRAPH
    this.barChartLabels = roleLabels;
    this.barChartData[0].data = employeeCountData;

    // Update the chart data and labels for PIE GRAPH
    this.pieChartLabels = roleLabels;
    this.pieChartData[0].data = employeeCountData;

  }

  filterByEmployeeRole(role: string) 
  {
    if (role === 'all') {
      this.isFilterActive = false;
    } else {
      this.filteredEmployees = this.employees.filter(item => item.employeeRoleName === role);
      this.isFilterActive = true;
    }
  }

  filterByEmployeeGender(gender: string) 
  {
    if (gender === 'all') {
      this.isFilterActive = false;
    } else {
      this.filteredEmployees = this.employees.filter(item => item.genderName === gender);
      this.isFilterActive = true;
    }
  }

  downloadPDF() {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text('Employee Report', 105, 25, { align: 'center' });
  
    // Add logo to the top left corner of the first page
    const logoImageUrl = 'assets/Pictures/Logo Black.png'; 
    const logoWidth = 10; 
    const logoHeight = 10; 
    doc.addImage(logoImageUrl, 'PNG', 100, 5, logoWidth, logoHeight);

    // Get the current date
    const currentDate = this.formatDate(new Date());
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setFontSize(10);
    doc.text(`Downloaded on: ${currentDate}`, pageWidth - 70, 10);

    // Add user name to report
    this.userService.getFullNameFromStore()
    .subscribe(val=>{
      const fullNameFromToken = this.auth.getfullNameFromToken();
      this.userName = val || fullNameFromToken
    });

    doc.setFontSize(10);
    doc.text(`Generated by: ${this.userName}`, pageWidth - 70, 15 )

    const headers = [['ID', 'Name', 'Surname', 'Gender', 'Role', 'Email Address', 'Physical Address', 'Phone Number', 'Employment Date']];
    
    // Default: Display all employees
    let employeesToDisplay = this.employees; 
  
    // Display filtered employees
    if (this.isFilterActive) {
      employeesToDisplay = this.filteredEmployees; 
    }

    const data = employeesToDisplay.map(employees => [
      employees.employeeId, 
      employees.firstName, 
      employees.surname, 
      employees.genderName,
      employees.employeeRoleName,
      employees.email_Address, 
      employees.physical_Address, 
      employees.phoneNumber,
      employees.employment_Date instanceof Date ? employees.employment_Date.toDateString() : ''
    ]);
  
    doc.setFontSize(12);

    // Adjust the Y position to leave space below the logo
    let startY = 40; 
  
    // Generate headers
    doc.autoTable({
      head: [headers],
      //margin: {top: 10},
      startY,
    });

    // Increment Y position for the next row
    startY += 10; 

    // Generate rows
    data.forEach((row) => {
      // Check if the page height will be exceeded
      if (startY + 10 > doc.internal.pageSize.height) {
        // Add a new page
        doc.addPage();
        startY = 20; // Reset Y position
      }

      // Generate the table row
      doc.autoTable({
        body: [row,[{ theme: 'grid'}]], 
        startY,
      });
        
      // Increment Y position for the next row
      startY += 10; 
    });
  
    // Convert the PDF blob to a Base64 string
    const pdfBlob = doc.output('blob');
  
    // Create a file-saver Blob object
    const file = new Blob([pdfBlob], { type: 'application/pdf' });
  
    // Save the Blob to a file
    saveAs(file, 'employee_report.pdf');
  }

  // Formatting the date for the report
  formatDate(date: Date): string
  {
    const day = date.getDate();
    const month = date.toLocaleString('default', { month: 'long'});
    const year = date.getFullYear();
    return `${day} ${month} ${year}`;
  }
}
