import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { SupplierService } from 'src/app/service/supplier.service';
import { Chart, ChartOptions, ChartType, ChartDataset } from 'chart.js';
import { BaseChartDirective } from 'ng2-charts';
import { Supplier } from 'src/app/shared/supplier';
import { Supplier_Inventory } from 'src/app/shared/supplieritem';
import { SupplierType } from 'src/app/shared/SupplierTypes'
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { saveAs } from 'file-saver';
import { UserStoreService } from 'src/app/UserService/user-store.service';
import { AuthService } from 'src/app/UserService/auth.service';

@Component({
  selector: 'app-supplier',
  templateUrl: './supplier.component.html',
  styleUrls: ['./supplier.component.css']
})
export class SupplierComponent implements OnInit {
  supplier: Supplier[] = [];
  supplierType: SupplierType[] = [];
  filteredSuppliers: Supplier[] = [];
  userName: string = "";

  isFilterActive = false;

  constructor(private http: HttpClient, 
    private supplierService: SupplierService, 
    private userService: UserStoreService,
    private auth: AuthService) { }

  ngOnInit() 
  {
    this.fetchData()
  }

  fetchData() 
  {
    this.supplierService.GetAllSupplierTypes().subscribe(result => {
      this.supplierType = result; 
      this.GetAllSuppliers(); 
    });
  }

  GetAllSuppliers() 
  {
    this.supplierService.GetAllSuppliers().subscribe(result => {
      this.supplier = result;
    });
  }  

  filterBySupplierType(type: string) 
  {
    if (type === 'all') {
      this.isFilterActive = false;
    } else {
      this.filteredSuppliers = this.supplier.filter(item => item.supplierTypeName === type);
      this.isFilterActive = true;
    }
  }

  downloadPDF() {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text('Supplier Report', 105, 25, { align: 'center' });
  
    // Add logo to the top left corner of the first page
    const logoImageUrl = '/assets/Pictures/Logo Black.png'; 
    const logoWidth = 10; 
    const logoHeight = 10; 
    doc.addImage(logoImageUrl, 'PNG', 100, 5, logoWidth, logoHeight);
    
    // Get the current date
    const currentDate = this.formatDate(new Date());
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setFontSize(10);
    doc.text(`Downloaded on: ${currentDate}`, pageWidth - 70, 10);

    // Add user name to report
    this.userService.getFullNameFromStore()
    .subscribe(val=>{
      const fullNameFromToken = this.auth.getfullNameFromToken();
      this.userName = val || fullNameFromToken
    });

    doc.setFontSize(10);
    doc.text(`Generated by: ${this.userName}`, pageWidth - 70, 15 )

    const headers = [['ID', 'Name', 'Type', 'Email Address', 'Physical Address', 'Phone Number']];
    
    // Default: Display all suppliers
    let suppliersToDisplay = this.supplier; 
  
    // Display filtered suppliers
    if (this.isFilterActive) {
      suppliersToDisplay = this.filteredSuppliers; 
    }

    const data = suppliersToDisplay.map(supplier => [
      supplier.supplierId, 
      supplier.supplierName, 
      supplier.supplierTypeName, 
      supplier.email_Address, 
      supplier.physical_Address, 
      supplier.phoneNumber
    ]);
  
    doc.setFontSize(12);
  
    // To leave space below the logo
    let startY = 40; 
  
    // Generate headers
    doc.autoTable({
      head: headers,
      startY,
    });

    // Increment Y position for the next row
    startY += 10; 

    // Generate rows
    data.forEach((row) => {
      // Check if the page height will be exceeded
      if (startY + 10 > doc.internal.pageSize.height) {
        // Add a new page
        doc.addPage();
        // Reset Y position
        startY = 20; 
      }

      // Generate the table row
      doc.autoTable({
        body: [row],
        startY,
      });
        
      // Increment Y position for the next row
      startY += 10; 
    });
  
    // Convert the PDF blob to a Base64 string
    const pdfBlob = doc.output('blob');
  
    // Create a file-saver Blob object
    const file = new Blob([pdfBlob], { type: 'application/pdf' });
  
    // Save the Blob to a file
    saveAs(file, 'supplier_report.pdf');
  }

  // Formatting the date for the report
  formatDate(date: Date): string
  {
    const day = date.getDate();
    const month = date.toLocaleString('default', { month: 'long'});
    const year = date.getFullYear();
    return `${day} ${month} ${year}`;
  }
}
